#!/usr/bin/env python

## Fonty Python Copyright (C) 2006-2017 Donn.C.Ingle
## Contact: donn.ingle@gmail.com - I hope this email lasts.
##
## This file is part of Fonty Python.
## Fonty Python is free software: you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
##
## Fonty Python is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with Fonty Python.  If not, see <http://www.gnu.org/licenses/>.

"""
This is step 1 in the startup process.

Next is step 2: fp_step_2.py

This file exists to test that Python is version 2.

This file is kept simple so that it parses as either
version of Python. For that reason there are no imports
to fetch i18n etc.
"""
import sys

if sys.version_info >= (3, 0):
    sys.stdout.write(
            "Sorry, fontypython requires Python 2.x, " \
            "you are using Python 3.x\n" \
            "From the command line, try:\n" \
            "python2 fontypython\n" )
              
    sys.exit(1)

if __name__ == "__main__":
    import fp_step_2 
